#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

duration=60
profile=""

opts=$(getopt -q -o "" --longoptions "duration:,profile:" -n "getopt.sh" -- "$@")
eval set -- "$opts"
while true; do
    case "$1" in
        --duration)
            shift
            duration=$1
            shift
            ;;
        --profile)
            shift
            profile=$1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            shift
            ;;
    esac
done

if [ "$profile" == "sweep" ]; then
    echo "-1"
else
    echo "$duration"
fi
