#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
exec >vllm-server-stop-stderrout.txt 2>&1

echo "args: $@"
echo "hostname: $(hostname)"

if [ -e vllm-server.pid ]; then
    pid=$(cat vllm-server.pid)
    echo "Stopping vLLM server pid $pid"
    kill -15 $pid
    sleep 5
    if [ -e /proc/$pid ]; then
        echo "Server still running, sending SIGKILL"
        kill -9 $pid
    fi
    for f in vllm-server-output.txt vllm-server-stderrout.txt; do
        if [ -e "$f" ]; then
            echo "Compressing: $f"
            xz -3 -T 0 "$f"
        fi
    done
else
    echo "vllm-server.pid not found"
    echo "PWD: $(pwd)"
    echo "LS:"
    /bin/ls -l
    exit 1
fi
